
#This category holds general values that will mostly be customized by most.
["Starting Configurations"]
	#When this is true, you will lose hearts when killed by a mob. Otherwise, you can lose max hearts just by any sorts of death.
	"Lose Hearts Only When Killed By a Mob:" = false
	#This value modifies how many hearts you'll start at in a world. 2 would mean 1 extra heart, -2 would mean 1 less heart. If you have lives enabled, you'll gain a life when you get max hearts double your starting hearts. EX: If 3 hearts is your starting value, you'll gain a life if you get 3 more hearts. 
	#Range: > -19
	"Starting HitPoint Difference:" = 0
	#This values modifies the amount of hit points that should be lost when you die. The same also applies when you gain max health from lifestealing. 2 hit points = 1 health.
	#Range: > 1
	"Amount of HitPoints/Health Lost/Given Upon Death/Kill:" = 2
	#This value determines if a PLAYER should lose HEARTS AT ALL.
	"Disable Heart Loss:" = false
	#This introduces a new lives system where when a player loses all their max hearts, they will lose a life and their max hearts will reset. When they lose all their lives, they permanently die. You can gain a life if your max hearts are double your starting hearts. Setting this to -1 will disable this feature.
	#Range: > -1
	"Starting Lives:" = 0
	#When this is false, you will lose hearts when killed by anything. Otherwise, you can only lose max hearts when killed by a player.
	"Lose Hearts Only When Killed By a Player:" = false
	#When this is false, players that lose all lives/hearts will go into spectator mode. Otherwise, they'll be banned until unbanned.
	"Should Players get Banned When They Lose all Lives/Hearts:" = false

#This category is the configuration for items and enchantments in this mod
["Items and Enchantments"]
	#If you just want the generic Lifesteal mod, you can disable this and nobody can gain hearts through Heart Crystals but only through lifestealing.
	"Disable Heart Crystals:" = true
	#The percentage of max health a heart core should heal when used.
	#Range: 0.01 ~ 1.0
	"Percentage of max Health Heart Core Heals" = 0.25
	#This is the amount of hit points a Heart Crystal should give when used. 2 HitPoints = 1 Heart, 3 = 1.5 Heart.
	#Range: > 1
	"Amount of HitPoints Heart Crystal Permanently Gives:" = 2
	#This value determines whether modded enchantments from this mod should be disabled or not.
	"Disable Enchantments:" = true
	#Heart Cores can heal on default 25% of your health if right clicked. This value determines if they should be disabled.
	"Disable Heart Cores:" = true

#This category is everything related to life stealing from someone.
["Lifesteal Related"]
	#This value determines if a player should still earn hearts from a player they killed even if the player doesn't have hearts to spare. EX: MinimumHeartHave or disableHeartLoss settings
	"Players Gain Hearts From No Heart Players:" = false
	#This option changes the entire mod into more of a permanent heart gaining system. This makes it so nobody can gain hearts from lifestealing but ONLY through Heart Crystals. MOBS can still take your hearts away if they kill you though, UNLESS you have that option disabled.
	"Disable Lifesteal:" = false

#This category will hold the maximums for certain values
["Maximums and Minimums"]
	#WARNING: THIS IS INCOMPATIBLE WITH LIVES. IF YOU ENABLE BOTH, LIVES WILL AUTOMATICALLY BE DISABLED. This value makes a limit SET after your Starting HitPoint Difference for how many hit points/hearts a player can get. 2 hit points = 1 heart. Set this to less than 1 to disable the feature.
	#Range: > -1
	"Maximum Amount of Health/Hitpoints a Player can get:" = -1
	#WARNING: THIS IS INCOMPATIBLE WITH LIVES. IF YOU ENABLE BOTH, LIVES WILL AUTOMATICALLY BE DISABLED. This value makes a limit set on how many hit points/hearts a player can lose, this value is actually set depending on the Starting Health Difference. EX: Starting Health Difference - MinimumHeartHave. Set this to less than 0 to disable the feature.
	#Range: > -1
	"Minimum Amount Of Health/Hitpoints a Player can Lose:" = -1

#This category holds values that aren't intended for gameplay and aren't polished, but can be used to test certain aspects of the mod easily or just for good fun.
["MISC/FUN"]
	#When this is false, you can only gain hearts from killing players. Otherwise, any mob will give you hearts.
	"Killing any Mobs Gives Hearts:" = false

